Add blah-blah
masontikhonov/scaling-spoon pull request #1
Opened 2022-04-10 11:10 UTC by masontikhonov

This PR adds new functionality: it's logs `blah-blah`.

2022-04-10 11:14 UTC, PavelTsikhanau requested changes

2022-04-10 11:14 UTC, PavelTsikhanau commented on index.js
> +console.log('blah-blah');
Add `!`

2022-04-10 11:15 UTC, masontikhonov commented on index.js
> +console.log('blah-blah');
Good catch, thanks!

2022-04-10 11:19 UTC, PavelTsikhanau approved these changes

2022-04-10 11:20 UTC, merged

2022-05-22 08:57 UTC, PavelTsikhanau commented
Привет, я на связи, присылай ссылку. Мобильника нету

вс, 10 апр. 2022 г. в 15:20, Zhenya Tikhonov ***@***.***>:

> Merged #1 <https://github.com/masontikhonov/scaling-spoon/pull/1> into
> dev.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/masontikhonov/scaling-spoon/pull/1#event-6403696049>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYMU4STHXPQZMQNNUAJC7A3VEK2PFANCNFSM5TAVQIVQ>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>